name: release

on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v5
        with:
          java-version: adopt@1.11
      - uses: actions/setup-node@v1
        with:
          node-version: "13.x"
          registry-url: "https://registry.npmjs.org"

      - name: Check AAS
        working-directory: ./csw-aas-js
        run: |
          npm ci
          npm run build

      - name: Check Config App
        working-directory: ./csw-aas-js-examples/config-app
        run: |
          npm ci
          npm run build

      - name: Check Example App
        working-directory: ./csw-aas-js-examples/example-app
        run: |
          npm ci
          npm run build

      - name: Selenium Test
        run: sbt clean test
        env:
          CSW_VERSION: "50b46f322f" # Chnage before releasing (before tagging repo)

      - name: NPM Publish
        working-directory: ./csw-aas-js
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Github Release
        run: sbt -Dprod.publish=true githubRelease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_RELEASE }}

      - name: Docs Publish
        run: |
          echo 'echo $GITHUB_RELEASE' > /tmp/.git-askpass
          chmod +x /tmp/.git-askpass
          git config --global user.email "actions@github.com"
          git config --global user.name "Github Action"
          sbt -Dprod.publish=true clean ghpagesPushSite

        env:
          GITHUB_RELEASE: ${{ secrets.GITHUB_RELEASE }}
          GIT_ASKPASS: /tmp/.git-askpass

      - name: Notify slack
        if: always()
        continue-on-error: true
        uses: kpritam/slack-job-status-action@v1
        with:
          job-status: ${{ job.status }}
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel: csw-prod-release
